### ISSUE TITLE
Erro 429 na pesquisa.

### ISSUE THREAD

**Issue by renatocfrancisco** [NatanaelAntonioli/CaptainFrogTorrentFinder#3]
Se tiver um nome melhor para essa "issue", por favor.
Eu não estou conseguindo executar a pesquisa. Acredito ser o navegador colocando um Captcha ou ele só impede a pesquisa devido às requisições do bot.
Às vezes, eu consigo pegar os links, às vezes dá esse problema.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "main.py", line 11, in clicked
  File "torrent_search.py", line 152, in listar_torrents
  File "torrent_search.py", line 79, in get_list_of_torrents
  File "googlesearch\__init__.py", line 45, in search
  File "googlesearch\__init__.py", line 18, in _req
  File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DFrank%252BSinatra%2522magnet%2522%26num%3D12%26hl%3Den%26start%3D0&hl=en&q=EhAoBAOJICzy2pRTm63yKaoxGIfH1ZcGIhAZN5hAXV85hjwk6WITwibPMgFy
```

**Comment by reisaraujo-miguel** [comment]
Mesmo problema aqui:
```
Erro no provedor sld
Erro no provedor tpb
Erro no provedor tgy
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/leug/scripts/CaptainFrogTorrentFinder/main.py", line 11, in clicked
    handlers= listar_torrents(inp)
  File "/home/leug/scripts/CaptainFrogTorrentFinder/torrent_search.py", line 152, in listar_torrents
    torrents = get_list_of_torrents(lista_provedores, buscar)
  File "/home/leug/scripts/CaptainFrogTorrentFinder/torrent_search.py", line 79, in get_list_of_torrents
    for j in search(query):
  File "/home/leug/.local/lib/python3.10/site-packages/googlesearch/__init__.py", line 45, in search
    resp = _req(escaped_term, num_results-start, lang, start, proxies)
  File "/home/leug/.local/lib/python3.10/site-packages/googlesearch/__init__.py", line 18, in _req
    resp.raise_for_status()
  File "/home/leug/.local/lib/python3.10/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dthor%250Athor%2522magnet%2522%26num%3D12%26hl%3Den%26start%3D0&hl=en&q=EgSE_21UGJ2-3pcGIhCZdx-BAprB2zfZsQ43DREpMgFy
```

**Comment by anti-duhring** [comment]
Nesse caso é o Google impedindo o tráfego por conta da quantidade alta de requisições que o bot já fez. 

Alguém sabe se o Natan tá aceitando novos PRs? Um `try` e `except`  envolvendo o loop na linha `79` deve resolver pra evitar que o programa quebre com o traceback.

Assim:
```python
try:
    for j in search(query):
            try:
                req = Request(j, headers={'User-Agent': 'Sapo'})
                webpage = urlopen(req).read()

                texto_pagina = webpage.decode('ISO-8859-1')

                lista_split = texto_pagina.split('"')[1:-1]

                for i in (lista_split):
                    if "magnet:?" in i:
                        pure = i
                        i = i.replace("&#", "=")
                        i = i.replace("x3D;", "")
                        i = i.replace("amp;", "")

                        if i not in lista_magnets_main and i not in lista_magnets_second and verify_magnet_link(i):
                            lista_magnets_google.append([i, i, "G"])
            except:
                print("Erro na página " + j)
except:
    print('Erro ao fazer request')
```

**Comment by anti-duhring** [comment]
Criei um PR pra isso https://github.com/NatanaelAntonioli/CaptainFrogTorrentFinder/pull/6

Impede o traceback e mostra uma mensagem de erro:
![image](https://user-images.githubusercontent.com/99638905/187771392-5f137631-fe73-43ab-8485-715bb0dfaa08.png)
